source "https://rubygems.org"

gem 'jekyll', '~> 4.3', '>= 4.3.3'
gem 'just-the-docs', '~> 0.8.0'

gem 'webrick', '1.8.1'  # required for ruby 3.0+
gem 'wdm', '0.1.1', :platforms => [:mingw, :x64_mingw, :mswin]
